version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    container_name: dropbot-mongodb
    ports:
      - 27017:27017
    networks: 
      - container-network
    volumes:
      - mongodb_data_container:/data/db

volumes:
  mongodb_data_container:

networks: 
  container-network:
    name: container-network
    driver: bridge