export enum As7aActions {
  AS7a_AWAIT_BLOCKS = 'AS7a_AWAIT_BLOCKS',
  AS7a_SYNC_BALANCES_WITH_BLOCKCHAIN = 'AS7a_SYNC_BALANCES_WITH_BLOCKCHAIN',

  AS7a_PRE_SEQUENCE_CHECK = 'AS7a_PRE_SEQUENCE_CHECK',
  AS7a_POST_SEQUENCE_CHECK = 'AS7a_POST_SEQUENCE_CHECK',

  AS7a_PRE_SYNCSWAP_SWAP_CHECK = 'AS7a_PRE_SYNCSWAP_SWAP_CHECK',
  AS7a_SYNCSWAP_SWAP = 'AS7a_SYNCSWAP_SWAP',
  AS7a_POST_SYNCSWAP_SWAP_CHECK = 'AS7a_POST_SYNCSWAP_SWAP_CHECK',
}
