export enum As7bActions {
  AS7b_AWAIT_BLOCKS = 'AS7b_AWAIT_BLOCKS',

  AS7b_SYNC_BALANCES_WITH_BLOCKCHAIN = 'AS7b_SYNC_BALANCES_WITH_BLOCKCHAIN',

  AS7b_PRE_SEQUENCE_CHECK = 'AS7b_PRE_SEQUENCE_CHECK',
  AS7b_POST_SEQUENCE_CHECK = 'AS7b_POST_SEQUENCE_CHECK',

  AS7b_PRE_SYNCSWAP_SWAP_CHECK = 'AS7b_PRE_SYNCSWAP_SWAP_CHECK',
  AS7b_SYNCSWAP_SWAP = 'AS7b_SYNCSWAP_SWAP',
  AS7b_POST_SYNCSWAP_SWAP_CHECK = 'AS7b_POST_SYNCSWAP_SWAP_CHECK',
}
