export enum As7cActions {
  AS7c_AWAIT_BLOCKS = 'AS7c_AWAIT_BLOCKS',

  AS7c_SYNC_BALANCES_WITH_BLOCKCHAIN = 'AS7c_SYNC_BALANCES_WITH_BLOCKCHAIN',

  AS7c_PRE_SEQUENCE_CHECK = 'AS7c_PRE_SEQUENCE_CHECK',
  AS7c_POST_SEQUENCE_CHECK = 'AS7c_POST_SEQUENCE_CHECK',

  AS7c_PRE_SYNCSWAP_SWAP_CHECK = 'AS7c_PRE_SYNCSWAP_SWAP_CHECK',
  AS7c_SYNCSWAP_SWAP = 'AS7c_SYNCSWAP_SWAP',
  AS7c_POST_SYNCSWAP_SWAP_CHECK = 'AS7c_POST_SYNCSWAP_SWAP_CHECK',
}
