export enum As7dActions {
  AS7d_AWAIT_BLOCKS = 'AS7d_AWAIT_BLOCKS',

  AS7d_SYNC_BALANCES_WITH_BLOCKCHAIN = 'AS7d_SYNC_BALANCES_WITH_BLOCKCHAIN',

  AS7d_PRE_SEQUENCE_CHECK = 'AS7d_PRE_SEQUENCE_CHECK',
  AS7d_POST_SEQUENCE_CHECK = 'AS7d_POST_SEQUENCE_CHECK',

  AS7d_PRE_SYNCSWAP_SWAP_CHECK = 'AS7d_PRE_SYNCSWAP_SWAP_CHECK',
  AS7d_SYNCSWAP_SWAP = 'AS7d_SYNCSWAP_SWAP',
  AS7d_POST_SYNCSWAP_SWAP_CHECK = 'AS7d_POST_SYNCSWAP_SWAP_CHECK',
}
