export enum Blockchains {
  ARBITRUM_ONE = 'ARBITRUM_ONE',
  POLYGON_MUMBAI = 'POLYGON_MUMBAI',
  POLYGON = 'POLYGON',
  ZKSYNC_SEPOLIA_TESTNET = 'ZKSYNC_SEPOLIA_TESTNET',
  ZKSYNC_GOERLI_TESTNET = 'ZKSYNC_GOERLI_TESTNET',
  ZKSYNC = 'ZKSYNC',
  ETHEREUM = 'ETHEREUM',
  SEPOLIA = 'SEPOLIA',
  BASE = 'BASE',
  POLYGON_ZKEVM_TESTNET = 'POLYGON_ZKEVM_TESTNET',
}

export enum ChainIds {
  ARBITRUM_ONE = '42161',
  POLYGON_MUMBAI = '80001',
  POLYGON = '137',
  ZKSYNC_SEPOLIA_TESTNET = '300',
  ZKSYNC_GOERLI_TESTNET = '280',
  ZKSYNC = '324',
  ETHEREUM = '1',
  SEPOLIA = '11155111',
  BASE = '8453',
  POLYGON_ZKEVM_TESTNET = '1442',
}
