export enum Flow1Actions {
  PRE_SEQUENCE_CHECK = 'FLOW_1_PRE_SEQUENCE_CHECK',
  POST_SEQUENCE_CHECK = 'FLOW_1_POST_SEQUENCE_CHECK',

  WRAP_NATIVE_IN = 'FLOW_1_WRAP_NATIVE_IN',
  WRAP_NATIVE_OUT = 'FLOW_1_WRAP_NATIVE_OUT',
  POST_WRAP_NATIVE_IN_CHECK = 'FLOW_1_POST_WRAP_NATIVE_IN_CHECK',
  POST_WRAP_NATIVE_OUT_CHECK = 'FLOW_1_POST_WRAP_NATIVE_OUT_CHECK',

  AWAIT_BLOCKS = 'FLOW_1_AWAIT_BLOCKS',

  EMAIL = 'FLOW_1_EMAIL',
}
