export enum HoudiniActions {
  HOUDINI_GET_SUPPORTED_TOKENS = 'HOUDINI_GET_SUPPORTED_TOKENS',
  HOUDINI_GET_QUOTE = 'HOUDINI_GET_QUOTE',
  HOUDINI_GET_EXCHANGE_ADDRESS = 'HOUDINI_GET_EXCHANGE_ADDRESS',
  HOUDINI_SEND_TOKENS = 'HOUDINI_SEND_TOKENS',
  HOUDINI_SEND_STATUS = 'HOUDINI_SEND_STATUS',
}
