export enum PolygonMumbaiActions {
  PRE_SEQUENCE_CHECK = 'PRE_SEQUENCE_CHECK',
  POST_SEQUENCE_CHECK = 'POST_SEQUENCE_CHECK',

  WRAP_NATIVE_IN = 'WRAP_NATIVE_IN',
  WRAP_NATIVE_OUT = 'WRAP_NATIVE_OUT',
  POST_WRAP_NATIVE_IN_CHECK = 'POST_WRAP_NATIVE_IN_CHECK',
  POST_WRAP_NATIVE_OUT_CHECK = 'POST_WRAP_NATIVE_OUT_CHECK',

  WRAP_WETH_IN = 'WRAP_WETH_IN',
  WRAP_WETH_OUT = 'WRAP_WETH_OUT',
  POST_WRAP_WETH_IN_CHECK = 'POST_WRAP_WETH_IN_CHECK',
  POST_WRAP_WETH_OUT_CHECK = 'POST_WRAP_WETH_OUT_CHECK',

  PRE_UNISWAP_V2_CHECK = 'PRE_UNISWAP_V2_CHECK',
  UNISWAP_V2_SWAP = 'UNISWAP_V2_SWAP',
  PRE_BRIDGE_CHECK = 'PRE_BRIDGE_CHECK',

  PRE_UNISWAP_V3_CHECK = 'PRE_UNISWAP_V3_CHECK',
  UNISWAP_V3_SWAP = 'UNISWAP_V3_SWAP',

  AWAIT_BLOCKS = 'AWAIT_BLOCKS',
}
