export enum PolygonActions {
  PRE_SEQUENCE_CHECK = 'PRE_SEQUENCE_CHECK',
  POST_SEQUENCE_CHECK = 'POST_SEQUENCE_CHECK',

  WRAP_NATIVE_IN = 'WRAP_NATIVE_IN',
  WRAP_NATIVE_OUT = 'WRAP_NATIVE_OUT',
  POST_WRAP_NATIVE_IN_CHECK = 'POST_WRAP_NATIVE_IN_CHECK',
  POST_WRAP_NATIVE_OUT_CHECK = 'POST_WRAP_NATIVE_OUT_CHECK',

  PRE_UNISWAP_V3_SWAP_CHECK = 'PRE_UNISWAP_V3_SWAP_CHECK',
  UNISWAP_V3_SWAP = 'UNISWAP_V3_SWAP',
  POST_UNISWAP_V3_SWAP_CHECK = 'POST_UNISWAP_V3_SWAP_CHECK',

  PRE_BRIDGE_CHECK = 'PRE_BRIDGE_CHECK',

  AWAIT_BLOCKS = 'AWAIT_BLOCKS',

  POLYGON_ORBITER_BRIDGE = 'POLYGON_ORBITER_BRIDGE',
}
